### Create AppUser


### Create a new app user (valid)
POST {{base_url}}/api/club/app-users
Authorization: Bearer {{token_club_user}}
Content-Type: application/json
Accept: application/json

{
    "name": "Juan",
    "last_name": "Perez",
    "phone_number": "987654322",
    "birthday": "2000-01-01",
    "gender": "male",
    "email": "JuanpereZ@example.com"
}
### Another app user
POST {{base_url}}/api/club/app-users
Authorization: Bearer {{token_club_user}}
Content-Type: application/json
Accept: application/json

{
    "name": "Maria",
    "last_name": "Gomez",
    "phone_number": "123456792",
    "birthday": "1999-01-01",
    "gender": "female",
    "email": "mariagom@example.com"
}
