### Update AppUser

@app_user_id = 1

### Update app user (all fields)
PUT {{base_url}}/api/club/app-users/{{app_user_id}}
Authorization: Bearer {{token_club_user}}
Content-Type: application/json

{
  "name": "Juan Updated",
  "last_name": "Perez Updated",
  "phone_number": "3415550200",
  "email": "juan.updated@example.com",
  "birthday": "1992-06-10",
  "gender": "female"
}

### Update app user - keeping same email
PUT {{base_url}}/api/club/app-users/{{app_user_id}}
Authorization: Bearer {{token_club_user}}
Content-Type: application/json

{
  "name": "Juan",
  "last_name": "Perez",
  "phone_number": "3415550201",
  "email": "juan.perez@example.com",
  "birthday": "1995-05-20",
  "gender": "male"
}

### FAIL: Update app user - empty name
PUT {{base_url}}/api/club/app-users/{{app_user_id}}
Authorization: Bearer {{token_club_user}}
Content-Type: application/json

{
  "name": "",
  "last_name": "Perez",
  "phone_number": "3415550203",
  "email": "juan@example.com",
  "birthday": "1995-05-20",
  "gender": "male"
}

### FAIL: Update app user - future birthday
PUT {{base_url}}/api/club/app-users/{{app_user_id}}
Authorization: Bearer {{token_club_user}}
Content-Type: application/json

{
  "name": "Juan",
  "last_name": "Perez",
  "phone_number": "3415550204",
  "email": "juan@example.com",
  "birthday": "2999-01-01",
  "gender": "male"
}

### FAIL: Update app user - that doesn't belong to club
PUT {{base_url}}/api/club/app-users/9999
Authorization: Bearer {{token_club_user}}
Content-Type: application/json
Accept: application/json

{
  "name": "Juan",
  "last_name": "Perez",
  "phone_number": "3415550205",
  "email": "juan@example.com",
  "birthday": "1995-05-20",
  "gender": "male"
}

