PUT {{base_url}}/api/app/reset-password
Accept: application/json
Content-Type: application/json

{
    "token": "8792dcc9468e55558bf48352cecf52561bf5169b28873619ee3426304a04a8c1",
    "email": "jorge@example.com",
    "password": "ClubDemo12345!",
    "password_confirmation": "ClubDemo12345!"
}
