PUT {{base_url}}/api/app/reset-password
Accept: application/json
Content-Type: application/json

{
    "token": "7d7ed8087b92c54b0a286638ecbc69b5243041274178ef7ef12fcc45c3ced192",
    "email": "club.demo@example.com",
    "password": "ClubDemo12345!",
    "password_confirmation": "ClubDemo12345!"
}
