POST {{base_url}}/api/club/login
Content-Type: application/json
Accept: application/json

{
    "email": "club.demo@example.com",
    "password": "ClubDemo12345!"
}
> {% client.global.set("token_club_user", response.body); %}


###

