PUT {{base_url}}/api/club/reset-password
Accept: application/json
Content-Type: application/json

{
    "token": "/d45809aa01a88511154dce462da7884455806cbc68e27ee3103e7def3f6e8bf2",
    "email": "club.demo@example.com",
    "password": "ClubDemo12345!",
    "password_confirmation": "ClubDemo12345!"
}
