PUT {{base_url}}/api/admin/users/1/change-password
Authorization: Bearer {{token_admin_user}}
Accept: application/json
Content-Type: application/json

{
    "password": "P@ssword1234",
    "password_confirmation": "P@ssword1234"
}

