PUT {{base_url}}/api/admin/reset-password
Accept: application/json
Content-Type: application/json

{
    "token": "71287b1f65b01bc8a397bf5b217f12b35adf3d3323b981086142935dab6c339f",
    "email": "admin9@admin.com",
    "password": "123",
    "password_confirmation": "123"
}
